name: .NET

on:
  push:
    branches: [ main ]    
    paths-ignore:
    - 'doc/**'
    - '*.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./src
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./src
    - name: Pack with dotnet
      run: dotnet pack --output artifacts --configuration Release -p:PackageVersion=$GITHUB_RUN_ID      
      working-directory: ./src
    
